name: CI_Backend_to_ECR

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'backend/**'

jobs:
  build-and-push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: vitr/actions-build-and-upload-to-ecs@master
          with:
            access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            account_id: ${{ secrets.AWS_ACCOUNT_ID }}
            repo: aws-ecr-repo
            region: eu-north-1
            tags: latest,${{ github.sha }}
            create_repo: true
